### ISSUE TITLE
云日历签到失效

### ISSUE THREAD

**Issue by U1F357** [daimiaopeng/IthomeQianDao#10]
云日历显示已签到，但是并没有增加金币。

另外通过https://my.ruanmei.com/api/User.asmx/L
userHash=
extra=8|lapin_uwp_win或者7|qiyu_pc
可以实现辣品和旗鱼的登录，能领取经验。（但是extra=10|mytime_windows不能算作云日历登录，不晓得为啥）

**Comment by daimiaopeng** [comment]
> 云日历显示已签到，但是并没有增加金币。
> 
> 另外通过https://my.ruanmei.com/api/User.asmx/L
> userHash=
> extra=8|lapin_uwp_win或者7|qiyu_pc
> 可以实现辣品和旗鱼的登录，能领取经验。（但是extra=10|mytime_windows不能算作云日历登录，不晓得为啥）

这个我不想弄了，你改改吧

**Comment by zixing131** [comment]
抓包看一下就知道了
