### ISSUE TITLE
大佬，金币签到失效了

### ISSUE THREAD

**Issue by cantinzing** [daimiaopeng/IthomeQianDao#12]
7月10号后不行了

**Comment by Lorem3** [comment]
> 7月10号后不行了
我一直用的这个，还行
[https://signit.pages.dev/addUser](https://signit.pages.dev/addUser)

**Comment by cantinzing** [comment]
> > 7月10号后不行了
> > 我一直用的这个，还行
> > https://signit.pages.dev/addUser

谢谢老哥

**Comment by cantinzing** [comment]
> > 7月10号后不行了
> > 我一直用的这个，还行
> > https://signit.pages.dev/addUser

谢谢老哥，顺便问下能提供代码学习下吗

**Comment by daimiaopeng** [comment]
> > 7月10号后不行了
> > 我一直用的这个，还行
> > https://signit.pages.dev/addUser
我看log还可以签到
{'cdays': 564, 'remainday': 3, 'ok': 1, 'title': '签到成功', 'itype': 1, 'ntype': 2, 'message': {'签到奖励': '+10金币'}, 'coin': 10}

**Comment by cantinzing** [comment]
> > > 7月10号后不行了
> > > 我一直用的这个，还行
> > > https://signit.pages.dev/addUser
> > > 我看log还可以签到
> > > {'cdays': 564, 'remainday': 3, 'ok': 1, 'title': '签到成功', 'itype': 1, 'ntype': 2, 'message': {'签到奖励': '+10金币'}, 'coin': 10}

是我搞错了，我改了密码

**Comment by cantinzing** [comment]
> > > 7月10号后不行了
> > > 我一直用的这个，还行
> > > https://signit.pages.dev/addUser
> > > 我看log还可以签到
> > > {'cdays': 564, 'remainday': 3, 'ok': 1, 'title': '签到成功', 'itype': 1, 'ntype': 2, 'message': {'签到奖励': '+10金币'}, 'coin': 10}

大佬你用的哪个签到啊，我运行你的run.py提示{'ok': 0, 'msg': '因业务调整，仅支持IT之家App签到。'}，用这个https://signit.pages.dev/addUser登录不了，明明用户名和密码是正确的，把我整不会了

**Comment by daimiaopeng** [comment]
> > > > 7月10号后不行了
> > > > 我一直用的这个，还行
> > > > https://signit.pages.dev/addUser
> > > > 我看log还可以签到
> > > > {'cdays': 564, 'remainday': 3, 'ok': 1, 'title': '签到成功', 'itype': 1, 'ntype': 2, 'message': {'签到奖励': '+10金币'}, 'coin': 10}
> 
> 大佬你用的哪个签到啊，我运行你的run.py提示{'ok': 0, 'msg': '因业务调整，仅支持IT之家App签到。'}，用这个[https://signit.pages.dev/addUser登录不了，明明用户名和密码是正确的，把我整不会了](https://signit.pages.dev/addUser%E7%99%BB%E5%BD%95%E4%B8%8D%E4%BA%86%EF%BC%8C%E6%98%8E%E6%98%8E%E7%94%A8%E6%88%B7%E5%90%8D%E5%92%8C%E5%AF%86%E7%A0%81%E6%98%AF%E6%AD%A3%E7%A1%AE%E7%9A%84%EF%BC%8C%E6%8A%8A%E6%88%91%E6%95%B4%E4%B8%8D%E4%BC%9A%E4%BA%86)

![QQ_1721357020753](https://github.com/user-attachments/assets/7eb3474d-9458-4edb-8a7c-90f73f795519)

**Comment by cantinzing** [comment]
> > > > > 7月10号后不行了
> > > > > 我一直用的这个，还行
> > > > > https://signit.pages.dev/addUser
> > > > > 我看log还可以签到
> > > > > {'cdays': 564, 'remainday': 3, 'ok': 1, 'title': '签到成功', 'itype': 1, 'ntype': 2, 'message': {'签到奖励': '+10金币'}, 'coin': 10}
> > 
> > 
> > 大佬你用的哪个签到啊，我运行你的run.py提示{'ok': 0, 'msg': '因业务调整，仅支持IT之家App签到。'}，用这个[https://signit.pages.dev/addUser登录不了，明明用户名和密码是正确的，把我整不会了](https://signit.pages.dev/addUser%E7%99%BB%E5%BD%95%E4%B8%8D%E4%BA%86%EF%BC%8C%E6%98%8E%E6%98%8E%E7%94%A8%E6%88%B7%E5%90%8D%E5%92%8C%E5%AF%86%E7%A0%81%E6%98%AF%E6%AD%A3%E7%A1%AE%E7%9A%84%EF%BC%8C%E6%8A%8A%E6%88%91%E6%95%B4%E4%B8%8D%E4%BC%9A%E4%BA%86)
> 
> ![QQ_1721357020753](https://private-user-images.githubusercontent.com/32475719/350207893-7eb3474d-9458-4edb-8a7c-90f73f795519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTgwMzksIm5iZiI6MTcyMTM1NzczOSwicGF0aCI6Ii8zMjQ3NTcxOS8zNTAyMDc4OTMtN2ViMzQ3NGQtOTQ1OC00ZWRiLThhN2MtOTBmNzNmNzk1NTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAyNTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTc4NzY0ZmU3YTcxYzQzMDU2ODA3ZTNkZDMzNDg0ZDkyNDUxMzI5ZDlkYjBkYmI3NWRhY2FmNGZjMTliNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQWUaywx0UZ0emUEz6c5Nmka33otcVTj_SI73w7IzsA)

![image](https://github.com/user-attachments/assets/8da5e664-bfa5-444c-8317-eb0e42c7d086)
那应该是我手动签到了，导致14行是空的，其它的业务签到不行

**Comment by Lorem3** [comment]
> 密码

应该是ip拉黑了，现在应该好了
