### ISSUE TITLE
2020 年 3 月 7 日失效了

### ISSUE THREAD

**Issue by iBug** [daimiaopeng/IthomeQianDao#3]
我自己也写了一个签到脚本每天运行，但是 3 月 7 日起输出

```javascript
{
  "ok": 0,
  "msg": "签到失败，请升级最新版App后再试。"
}
```

简单看了一下最新版安卓 App 的二进制文件，签到用的 URL 没变，而且方式依然是 GET，但是我没找到现在该怎么签到。

**Comment by Lorem3** [comment]
因为他的签到链接不能重放了,每天的签到url不一样,应该是把日期之类的时间加密 ,不是今天的日期应该不能签到了

**Comment by cantinzing** [comment]
> 因为他的签到链接不能重放了,每天的签到url不一样,应该是把日期之类的时间加密 ,不是今天的日期应该不能签到了

是啊  ent参数每天都变。大佬有解决方法吗，他那个enc加密方法找不到

**Comment by daimiaopeng** [comment]
不好意思，现在才看见，已更新代码。

**Comment by daimiaopeng** [comment]
> 我自己也写了一个签到脚本每天运行，但是 3 月 7 日起输出
> 
> ```js
> {
>   "ok": 0,
>   "msg": "签到失败，请升级最新版App后再试。"
> }
> ```
> 
> 简单看了一下最新版安卓 App 的二进制文件，签到用的 URL 没变，而且方式依然是 GET，但是我没找到现在该怎么签到。

已解决，看最新代码

**Comment by Lorem3** [comment]
感觉不太厚道,把加密的方式都撸出来了.

**Comment by daimiaopeng** [comment]
这有什么，又没干坏事



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vittoz"; 
发送时间: 2020年7月3日(星期五) 上午10:47
收件人: "daimiaopeng/IthomeQianDao";
抄送: "daimiaopeng"<844362911@qq.com>;"State&nbsp;change";
主题: Re: [daimiaopeng/IthomeQianDao] 2020 年 3 月 7 日失效了 (#3)





  
不好意思，现在才看见，已更新代码。
 感觉不太厚道,把加密的方式都撸出来了.
  
&mdash;

**Comment by iBug** [comment]
7 月 4 日又失效了，会不会是 DES 密钥换了？

**Comment by daimiaopeng** [comment]
> 7 月 4 日又失效了，会不会是 DES 密钥换了？

换了加密，有时间再破解。

**Comment by daimiaopeng** [comment]
> 7 月 4 日又失效了，会不会是 DES 密钥换了？

已破解，最新密钥：qs$^w<4!
