### ISSUE TITLE
哈哈哈，找到一个，以后我就不破了，指望你破了

### ISSUE THREAD

**Issue by haodadajipai** [daimiaopeng/IthomeQianDao#5]
最新的qs$^w<4! 我刚从这里解出来：https://my.ruanmei.com/app/user/signinwechat.html?signtype=wechatapp&jssdklevel=2&hidemenu=1

**Comment by daimiaopeng** [comment]
我破了

**Comment by haodadajipai** [comment]
> 我破了

我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈

**Comment by daimiaopeng** [comment]
> > 我破了
> 
> 我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈

我更新了破解思路

**Comment by haodadajipai** [comment]
> > > 我破了
> > 
> > 
> > 我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈
> 
> 我更新了破解思路

果然，一样的思路。哈哈哈，之家要气死了，加密过的代码都硬看。

**Comment by daimiaopeng** [comment]
你用浏览器直接调试？

**Comment by daimiaopeng** [comment]
> > > > 我破了
> > > 
> > > 
> > > 我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈
> > 
> > 
> > 我更新了破解思路
> 
> 果然，一样的思路。哈哈哈，之家要气死了，加密过的代码都硬看。

你用浏览器直接调试？

**Comment by haodadajipai** [comment]
> > > > > 我破了
> > > > 
> > > > 
> > > > 我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈
> > > 
> > > 
> > > 我更新了破解思路
> > 
> > 
> > 果然，一样的思路。哈哈哈，之家要气死了，加密过的代码都硬看。
> 
> 你用浏览器直接调试？

是呀，他是qs$^w+<4! ，两个字符串拼接一起的。所以这就是你之前断点只看到前面的原因

**Comment by daimiaopeng** [comment]
> > > > > > 我破了
> > > > > 
> > > > > 
> > > > > 我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈
> > > > 
> > > > 
> > > > 我更新了破解思路
> > > 
> > > 
> > > 果然，一样的思路。哈哈哈，之家要气死了，加密过的代码都硬看。
> > 
> > 
> > 你用浏览器直接调试？
> 
> 是呀，他是qs$^w+<4! ，两个字符串拼接一起的。所以这就是你之前断点只看到前面的原因

浏览器不是直接报错吗？

**Comment by daimiaopeng** [comment]
![image](https://user-images.githubusercontent.com/32475719/86589916-20511700-bfc1-11ea-97e7-55936dc84785.png)

**Comment by haodadajipai** [comment]
> > > > > > > 我破了
> > > > > > 
> > > > > > 
> > > > > > 我看到了，所以以后就指望你了，之家肯定还会改的哈哈哈
> > > > > 
> > > > > 
> > > > > 我更新了破解思路
> > > > 
> > > > 
> > > > 果然，一样的思路。哈哈哈，之家要气死了，加密过的代码都硬看。
> > > 
> > > 
> > > 你用浏览器直接调试？
> > 
> > 
> > 是呀，他是qs$^w+<4! ，两个字符串拼接一起的。所以这就是你之前断点只看到前面的原因
> 
> 浏览器不是直接报错吗？

我没打断点，直接看源码调试的。还好，只是混淆了，拿着混淆的代码去调试就好

**Comment by daimiaopeng** [comment]
6

**Comment by haodadajipai** [comment]
> 6
之家肯定马上会改的，指不定就看着我们俩的对话呢，以后交给你了。
