### ISSUE TITLE
2020年7月7日，key又变了

### ISSUE THREAD

**Issue by zixing131** [daimiaopeng/IthomeQianDao#6]
KEY='HCa%Y|7#' 
这是新的key，明天继续跟踪

**Comment by zixing131** [comment]
有没有兴趣一起写个根据js自动获取key的脚本啊

**Comment by Lorem3** [comment]
大佬,我签到200天,你一开源,我就断了.我不管,你得对我负责到底

**Comment by daimiaopeng** [comment]
> 楼主,我签到200天,你一开源,我就断了.你得对我负责到底

现在我不更新了，他们也不会改密钥了吧
