### ISSUE TITLE
又改了。。。

### ISSUE THREAD

**Issue by ReslieJobs** [daimiaopeng/IthomeQianDao#8]
时间戳没有加密了，但是多了一窜参数，参数名和内容都是加密的，而且密钥也都不是原来的密钥。。。淦

**Comment by ReslieJobs** [comment]
好像是/1/f开头的8位随机密钥😓

**Comment by daimiaopeng** [comment]
我搞不动了

**Comment by Lorem3** [comment]
> 我搞不动了

所以,自动签到,终结了么

**Comment by daimiaopeng** [comment]
> > 我搞不动了
> 
> 所以,自动签到,终结了么

emmmm，过一段时间再看看吧，最近有点忙

**Comment by zixing131** [comment]
是根据时间戳生成的密钥，已经解开了，但是不方便发出来了

**Comment by Lorem3** [comment]
> 是根据时间戳生成的密钥，已经解开了，但是不方便发出来了
 独乐乐与众乐乐,孰乐?

**Comment by daimiaopeng** [comment]
> > 是根据时间戳生成的密钥，已经解开了，但是不方便发出来了
> > 独乐乐与众乐乐,孰乐?

我已经发出来了

**Comment by zixing131** [comment]
> > 是根据时间戳生成的密钥，已经解开了，但是不方便发出来了
> > 独乐乐与众乐乐,孰乐?

已经提交了新的代码

**Comment by ReslieJobs** [comment]
> > > 是根据时间戳生成的密钥，已经解开了，但是不方便发出来了
> > > 独乐乐与众乐乐,孰乐?
> 
> 我已经发出来了

> > > 是根据时间戳生成的密钥，已经解开了，但是不方便发出来了
> > > 独乐乐与众乐乐,孰乐?
> 
> 已经提交了新的代码

昨天我也在其它项目的issue里面看到了，有更详细的说明[https://github.com/chavyleung/scripts/issues/9#issuecomment-686983155](https://github.com/chavyleung/scripts/issues/9#issuecomment-686983155)
