### ISSUE TITLE
可否升级成云函数版本运行

### ISSUE THREAD

**Issue by fhqswcan** [daimiaopeng/IthomeQianDao#9]
可否升级成云函数版本运行

**Comment by daimiaopeng** [comment]
我有阿里云云函数版本的，不知道你要哪个云服务器公司的？

**Comment by daimiaopeng** [comment]
> 可否升级成云函数版本运行

我有阿里云云函数版本的，不知道你要哪个云服务器公司的？

**Comment by fhqswcan** [comment]
需要的是腾讯云函数

**Comment by daimiaopeng** [comment]
> 需要的是腾讯云函数

不好意思，腾讯云函数版本没有

**Comment by fhqswcan** [comment]
我可以根据阿里的改一下

**Comment by daimiaopeng** [comment]
> 我可以根据阿里的改一下

刚才看了一下代码，其实就是github代码，上传这个，设置定时触发器就行了

**Comment by fhqswcan** [comment]
好的 我试下
